### ISSUE TITLE
Partial Values for example-3

### ISSUE THREAD

**Issue by MonkeyIsNull** [anewton1998/redacted_examples#1]
My question is whether example-3 should have some string content in the fields that it designates as being redacted?
In section 3.3 of the draft we have:
```
3.3.  Redaction by Partial Value Method

   The Redaction by Partial Value Method is when a redacted field is not
   removed, but its value has a portion of the data removed, such as for
   the "label" or "fn" jCard [RFC7095] properties.  The partial values
   are referenced in the "redacted" member in place of the property name
   in a array, such as referencing the "fn" jCard [RFC7095] property
   value at position 3 instead of referencing the "fn" jCard property
   name at position 0.  The Redaction by Partial Value Method SHOULD be
   used only when redacting JSON response fields that use a formatted
   value, where a portion of the value is removed.

   An example of the "label" jCard property in Figure 15 of [RFC7095]
   that redacts "123 Maple Ave\nSuite 901\n":
   ["adr",
     {
       "type":"home",
       "label":"Vancouver\nBC\n1239\n"
     },
     "text",
     [
       "", "", "", "", "", "", ""
     ]
   ]

   An example of the "redacted" member for the redacted "label" jCard
   property value, based on Figure 15 of [RFC7095]:

   "redacted": [
     {
       "name": {
         "description": "Home Address Label"
       },
       "postPath": "$.vcardArray[1][?(@[0]=='adr')][1].label",
       "pathLang": "jsonpath",
       "method": "partialValue",
       "reason": {
         "description": "Server policy"
       }
     }
   ]
```

So I was under the impression that there should be _something_ there since it says a `portion` of the value is removed, not an empty value.

If we look at the five redactions in example-3 that are labeled partialValue, I have them all returning empty string:
"Registrant Name" `$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='fn')][3]` -> `[""]`
"Registrant Street" `$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][:3]` -> `["", "", ""]`
"Registrant City" `$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][3]` -> `[""]`
"Registrant Postal Code" `$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][5]` -> `[""]`
"Technical Name" `$.entities[?(@.roles[0]=='technical')].vcardArray[1][?(@[0]=='fn')][3]` -> `[""]`

So, do we want to add values to this record since this is an example? 
Even if we don't add anything in there, how should a client represent that? I am assuming it should acknowledge that something has been redacted just the same as EmptyValue.

**Comment by anewton1998** [comment]
#4 should fix this. Please let me know if it does not.
Please note that the first item in the registrant's address is still blank. I did that on purpose because in jCard that is the position for a PO Box and in all the RDAP examples you see it blank.
In other words, for partialValue the client will run into situations where the entire string is empty.
This kinda raises the question of why emptyValue and partialValue are separate methods and partialValue cannot identify the part is redacted.

**Comment by MonkeyIsNull** [comment]
Ok, great, that works. Thanks!

When I checked it I got:
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='fn')][3]` -> `[  "Bob"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][:3]` -> `[  "", "Suite", "4321"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][3]` ->  `[  "Que"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][5]` -> `[ "G1V-"  ]`
`$.entities[?(@.roles[0]=='technical')].vcardArray[1][?(@[0]=='fn')][3]` ->  `[  "Alice"  ]`

And when I run it through my code I get the following:
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='fn')][3]` -> `[  "*Bob*"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][:3]` -> `[  "*REDACTED*", "*Suite*", "*4321*"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][3]` ->  `[  "*Que*"  ]`
`$.entities[?(@.roles[0]=='registrant')].vcardArray[1][?(@[0]=='adr')][3][5]` -> `[ "*G1V-*"  ]`
`$.entities[?(@.roles[0]=='technical')].vcardArray[1][?(@[0]=='fn')][3]` -> `[ "*Alice*"  ]`

I did change the code so that if it claims it is partialValue and it gets empty string it will put `*REDACTED*` in there all the same, as you can see for the PO Box above.
